Assigned variable to do_plugin
I was running into issues with this on my local box so I just implemented a quick change to help. 

Error I was receiving:

Traceback (most recent call last):
  File "start.py", line 177, in <module>
    main(arguments)
  File "start.py", line 59, in main
    if do_plugin:
UnboundLocalError: local variable 'do_plugin' referenced before assignment

Thanks!